apiVersion: v1
baseDomain: doitall.local
compute: 
- name: worker
  replicas: 3
controlPlane:
  name: master
  replicas: 3
metadata:
  name: ocp4
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: |
 {"auths":{"util.ocp4.doitall.local:5000":{"auth".... 
sshKey: |
  ssh-rsa AAAAB3N....
imageContentSources:
- mirrors:
  - util.ocp4.doitall.local:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - util.ocp4.doitall.local:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
additionalTrustBundle: |
     -----BEGIN CERTIFICATE-----
 
     -----END CERTIFICATE-----
